version: '3'
services:
    product-app:
        container_name: product-app
        image: iatulb/productservice
        restart: on-failure
        ports: 
            - 9090:9090
        environment: 
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - my-mysql
            - coupon-app
    coupon-app:
        container_name: coupon-app
        image: iatulb/couponservice
        restart: on-failure
        ports: 
            - 9091:9091
        environment: 
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - my-mysql
    docker-mysql:
        container_name: my-mysql
        image: mysql
        restart: always
        environment: 
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: atul
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=test1234 --execute \"SHOW DATABASES \""
            interval: 4s
            timeout: 20s
            retries: 5
        
